# Generated by Django 2.2.28 on 2022-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default='images/no_image.png', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
